@RinhaBackEndNativeAot_HostAddress = http://localhost:8080

GET {{RinhaBackEndNativeAot_HostAddress}}/pessoas
Accept: application/json

###

GET {{RinhaBackEndNativeAot_HostAddress}}/pessoas/cecbfdf2-136c-4489-b093-8027cf74ca4b
Accept: application/json

###

POST {{RinhaBackEndNativeAot_HostAddress}}/pessoas/
Content-Type: application/json
Accept: application/json

{
    "Apelido": "Teste",
    "Nome": "Teste",
    "Nascimento": "1999-08-23",
    "Stack": ["Item1", "Item2"] 
}

###
