version: '3.8'

services:
  rinhabackend-api: &rinhabackend-api-config
    image: ${DOCKER_REGISTRY-}rinhabackend:latest
    container_name: rinhabackend-api
    depends_on:
      - db
    networks:
      - api_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  rinhabackend-api2:
    <<: *rinhabackend-api-config
    container_name: rinhabackend-api2
    depends_on:
      - db
      - rinhabackend-api

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Map the nginx.conf file
    depends_on:
      - rinhabackend-api
      - rinhabackend-api2
    networks:
      - api_network
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - api_network
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhabackend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.6GB'

  cache:
    image: redis:latest
    networks:
      - api_network
    ports:
      - '6379:6379' 
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.3GB'


networks:
  api_network:
    driver: bridge
