version: '3.8'

services:
  rinhabackend:
    image: ${DOCKER_REGISTRY-}rinhabackend:dev
    container_name: rinhabackend
    depends_on:
      - db
    networks:
      - api_network
    environment:
      - DATABASE_URL=postgres://db:5432/
    expose:
      - "80"

  rinhabackend2:
    image: ${DOCKER_REGISTRY-}rinhabackend:dev
    container_name: rinhabackend2
    depends_on:
      - db
      - rinhabackend
    networks:
      - api_network
    environment:
      - DATABASE_URL=postgres://db:5432/
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Map the nginx.conf file
    depends_on:
      - rinhabackend
      - rinhabackend2
    networks:
      - api_network
    ports:
      - "9999:9999"

  db:
    image: postgres:latest
    container_name: postgres_db
    networks:
      - api_network
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhabackend

networks:
  api_network:
    driver: bridge
