version: '3.8'

services:
  rinhabackend:
    image: ${DOCKER_REGISTRY-}rinhabackend:latest
    container_name: rinhabackend
    depends_on:
      - db
    networks:
      - api_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.6GB'

  rinhabackend2:
    image: ${DOCKER_REGISTRY-}rinhabackend:latest
    container_name: rinhabackend2
    depends_on:
      - db
      - rinhabackend
    networks:
      - api_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.6GB'

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Map the nginx.conf file
    depends_on:
      - rinhabackend
      - rinhabackend2
    networks:
      - api_network
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - api_network
    environment:
      - POSTGRES_USER=rinhabackend
      - POSTGRES_PASSWORD=rinhabackend
      - POSTGRES_DB=rinhabackend
    command: ["postgres", "-c", "max_connections=300"]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1.4GB'

  cache:
    image: redis:latest
    networks:
      - api_network
    ports:
      - '6379:6379' 
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.8GB'


networks:
  api_network:
    driver: bridge
